# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pixels', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='images')),
                ('content_type', models.CharField(max_length=50)),
                ('profile_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(default='0px', max_length=200)),
                ('left', models.CharField(default='0px', max_length=200)),
                ('color', models.CharField(default='transparent', max_length=200)),
                ('content_editable', models.BooleanField(default=True)),
                ('aria_disabled', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sketchboard.Canvases')),
            ],
        ),
        migrations.AddField(
            model_name='canvases',
            name='created_by',
            field=models.ManyToManyField(related_name='created_canvases', to='sketchboard.Profile'),
        ),
        migrations.AddField(
            model_name='canvases',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='sketchboard.Profile'),
        ),
    ]
